# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vim-bundler}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavel Tatarsky"]
  s.date = %q{2011-06-17}
  s.default_executable = %q{vbundle}
  s.description = %q{This gem provides a simple way to manage your vim bundles (aka plugins).
If you are familiar with ruby gem bundler - you are familar with vim-bundler.}
  s.email = %q{fazzzenda@mail.ru}
  s.executables = ["vbundle"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/vbundle",
    "lib/vim-bundler.rb",
    "lib/vim-bundler/actions.rb",
    "lib/vim-bundler/cli.rb",
    "lib/vim-bundler/dsl.rb",
    "lib/vim-bundler/git.rb",
    "lib/vim-bundler/installer.rb",
    "lib/vim-bundler/ui.rb",
    "lib/vim-bundler/vim_org.rb",
    "test/helper.rb",
    "test/test_vim-bundler.rb",
    "vim-bundler.gemspec"
  ]
  s.homepage = %q{http://github.com/vintikzzz/vim-bundler}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Bundler for vim}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

